project_id = "cqafqwcdhmydkqobznrf"

[functions.liveavatar-start]
verify_jwt = false

[functions.liveavatar-terminate]
verify_jwt = false

[functions.liveavatar-send-message]
verify_jwt = false

[functions.liveavatar-list-resources]
verify_jwt = false